# MCD Semantic Class Color Mapping
# Colors are specified as RGB values in range [0, 255]
# Based on MCD semantic label definitions
# Note: MCD uses 22 classes, but this file includes all possible class IDs (0-28)

# Class ID to RGB color mapping
# Format: class_id: [R, G, B]  # class_name
colors:
  "0": [128, 128, 128]  # barrier
  "1": [119, 11, 32]    # bike
  "2": [0, 100, 0]      # building
  "3": [139, 69, 19]    # chair
  "4": [101, 67, 33]    # cliff
  "5": [160, 160, 160]  # container
  "6": [244, 35, 232]   # curb
  "7": [190, 153, 153]  # fence
  "8": [255, 165, 0]    # hydrant
  "9": [255, 255, 0]    # infosign
  "10": [170, 255, 150] # lanemarking
  "11": [0, 0, 0]       # noise
  "12": [255, 255, 50]  # other
  "13": [250, 170, 160] # parkinglot
  "14": [220, 20, 60]   # pedestrian
  "15": [153, 153, 153] # pole
  "16": [128, 64, 128]  # road
  "17": [0, 100, 0]     # shelter
  "18": [244, 35, 232]  # sidewalk
  "19": [128, 0, 128]   # stairs
  "20": [0, 150, 255]   # structure-other
  "21": [255, 69, 0]    # traffic-cone
  "22": [0, 0, 255]     # traffic-sign
  "23": [139, 0, 139]   # trashbin
  "24": [0, 60, 135]    # treetrunk
  "25": [107, 142, 35]  # vegetation
  "26": [245, 150, 100] # vehicle-dynamic
  "27": [51, 0, 51]     # vehicle-other
  "28": [0, 0, 142]     # vehicle-static

# Class ID to name mapping (for reference)
class_names:
  "0": "barrier"
  "1": "bike"
  "2": "building"
  "3": "chair"
  "4": "cliff"
  "5": "container"
  "6": "curb"
  "7": "fence"
  "8": "hydrant"
  "9": "infosign"
  "10": "lanemarking"
  "11": "noise"
  "12": "other"
  "13": "parkinglot"
  "14": "pedestrian"
  "15": "pole"
  "16": "road"
  "17": "shelter"
  "18": "sidewalk"
  "19": "stairs"
  "20": "structure-other"
  "21": "traffic-cone"
  "22": "traffic-sign"
  "23": "trashbin"
  "24": "treetrunk"
  "25": "vegetation"
  "26": "vehicle-dynamic"
  "27": "vehicle-other"
  "28": "vehicle-static"

# Note: For ROS visualization, colors should be normalized to [0, 1] range
# Divide RGB values by 255.0 when converting to std_msgs/ColorRGBA
