# SemanticKITTI Semantic Class Color Mapping
# Colors are specified as RGB values in range [0, 255]
# Based on SemanticKITTI semantic label definitions

/**:
  ros__parameters:
    # Class ID to RGB color mapping (using actual SemanticKITTI label IDs)
    # Format: label_id: [R, G, B]  # class_name
    colors:
      # Special classes
      "0": [0, 0, 0]        # unlabeled
      "1": [0, 0, 255]      # outlier
      
      # Vehicles
      "10": [245, 150, 100] # car
      "11": [245, 230, 100] # bicycle
      "13": [250, 80, 100]  # bus
      "15": [150, 60, 30]   # motorcycle
      "16": [255, 0, 0]     # on-rails
      "18": [180, 30, 80]   # truck
      "20": [255, 0, 0]     # other-vehicle
      
      # Humans
      "30": [30, 30, 255]   # person
      "31": [200, 40, 255]  # bicyclist
      "32": [90, 30, 150]   # motorcyclist
      
      # Ground surfaces
      "40": [255, 0, 255]   # road
      "44": [255, 150, 255] # parking
      "48": [75, 0, 75]     # sidewalk
      "49": [75, 0, 175]    # other-ground
      
      # Structures
      "50": [0, 200, 255]   # building
      "51": [50, 120, 255]  # fence
      "52": [0, 150, 255]   # other-structure
      "60": [170, 255, 150] # lane-marking
      
      # Nature
      "70": [0, 175, 0]     # vegetation
      "71": [0, 60, 135]    # trunk
      "72": [80, 240, 150]  # terrain
      
      # Objects
      "80": [150, 240, 255] # pole
      "81": [0, 0, 255]     # traffic-sign
      "99": [255, 255, 50]  # other-object
      
      # Moving objects (optional, same colors as static)
      "252": [245, 150, 100] # moving-car
      "253": [200, 40, 255]  # moving-bicyclist
      "254": [30, 30, 255]   # moving-person
      "255": [90, 30, 150]   # moving-motorcyclist
      "256": [255, 0, 0]     # moving-on-rails
      "257": [250, 80, 100]  # moving-bus
      "258": [180, 30, 80]   # moving-truck
      "259": [255, 0, 0]     # moving-other-vehicle

    # Class ID to name mapping (using actual SemanticKITTI label IDs)
    class_names:
      "0": "unlabeled"
      "1": "outlier"
      "10": "car"
      "11": "bicycle"
      "13": "bus"
      "15": "motorcycle"
      "16": "on-rails"
      "18": "truck"
      "20": "other-vehicle"
      "30": "person"
      "31": "bicyclist"
      "32": "motorcyclist"
      "40": "road"
      "44": "parking"
      "48": "sidewalk"
      "49": "other-ground"
      "50": "building"
      "51": "fence"
      "52": "other-structure"
      "60": "lane-marking"
      "70": "vegetation"
      "71": "trunk"
      "72": "terrain"
      "80": "pole"
      "81": "traffic-sign"
      "99": "other-object"
      "252": "moving-car"
      "253": "moving-bicyclist"
      "254": "moving-person"
      "255": "moving-motorcyclist"
      "256": "moving-on-rails"
      "257": "moving-bus"
      "258": "moving-truck"
      "259": "moving-other-vehicle"

# Note: For ROS visualization, colors should be normalized to [0, 1] range
# Divide RGB values by 255.0 when converting to std_msgs/ColorRGBA
